#ifndef __FLASH_STRING_H__
#define __FLASH_STRING_H__

#include <Arduino.h>

char const BOMB_ERR_START[] PROGMEM = { "LA BOMBA NO ARRANCO -> SISTEMA DESHABILITADO" };
char const BOMB_ERR_STOP[] PROGMEM = { "LA BOMBA NO SE DETUVO -> PARADA DE EMERGENCIA ACTIVADA -> SISTEMA DESHABILITADO" };
char const BOMB_ERR_EMERGENCY_STOP[] PROGMEM = { "FALLO LA PARADA DE EMERGENCIA -> ASISTENCIA URGENTE BOMBA EN FUNCIONAMIENTO SIN CONTROL" };
char const BOMB_ERR_TIME_OUT[] PROGMEM = { "TIEMPO DE SEGURIDAD SUPERADO -> BOMBA DETENIDA -> SISTEMA DESHABILITADO" };
char const BOMB_ERR_STOP_MANUAL[] PROGMEM = {"ERROR PARADA MANUAL"};
char const BOMB_ERR_START_MANUAL[] PROGMEM = {"ERROR INICIO MANUAL"};
char const BOMB_STOP[] PROGMEM = {"FIN LLENADO -> BOMBA DETENIDA"};
char const BOMB_START[] PROGMEM = {"INICIO LLENADO -> BOMBA FUNCIONANDO"};
char const BOMB_MEDIUM_LOW[] PROGMEM = {"VACIANDO -> TANQUE A LA MITAD"};
char const BOMB_MEDIUM_HIGH[] PROGMEM = {"LLENANDO -> TANQUE A LA MITAD"};
char const BOMB_START_MANUAL[] PROGMEM = {"INICIO MANUAL -> BOMBA FUNCIONANDO"};
char const BOMB_STOP_MANUAL[] PROGMEM = {"PARADA MANUAL -> BOMBA DETENIDA"};
char const BOMB_ALREDY_ON[] PROGMEM = {"LA BOMBA YA SE ENCUENTRA EN FUNCIONAMIENTO"};
char const BOMB_ALREDY_OFF[] PROGMEM = {"LA BOMBA YA SE ENCUENTRA DETENIDA"};
char const BOMB_ACTUAL_ENABLED[] PROGMEM = {"EL SISTEMA SE ENCUENTRA HABILITADO"};
char const BOMB_ACTUAL_DISABLE[] PROGMEM = {"EL SISTEMA SE ENCUENTRA DESHABILITADO"};
char const BOMB_ENABLED[] PROGMEM = {"SISTEMA HABILITADO MANUALMENTE"};
char const BOMB_DISABLE[] PROGMEM = {"SISTEMA DESHABILITADO MANUALMENTE"};
char const BOMB_ERR_ENABLED[] PROGMEM = {"ERROR NO SE PUDO HABILITAR EL SISTEMA"};
char const BOMB_ERR_DISABLED[] PROGMEM = {"ERROR NO SE PUDO DESHABILITAR EL SISTEMA"};

char const GATEWAY_ERR_ORDER_PROCESS[] PROGMEM = {"EL SISTEMA YA ESTA PROCESANDO UNA ORDEN"};
char const GATEWAY_ERR_ORDER_INDETERMINATE[] PROGMEM = {"OCURRIO UN ERROR AL PROCESAR LA ORDEN, RESULTADO INDETERMINADO"};
char const GATEWAY_ERR_SALDO_MSG[] PROGMEM = { "NO ESTA CARGADO EL MENSAJE A ENVIAR PARA CONSULTAR EL SALDO" };
char const GATEWAY_ERR_SALDO_NUM[] PROGMEM = { "NO ESTA CARGADO EL NUMERO DE TELEFONO PARA CONSULTAR EL SALDO" };
char const GATEWAY_ERR_INIT[] PROGMEM = { "ERROR AL INCIAR PUERTA DE ENLACE" };
char const GATEWAY_ERR_GET_SALDO[] PROGMEM = { "NO SE PUDO OBTENER EL SALDO EN REITERADAS OCASIONES" };
char const GATEWAY_INIT_GPRS[] PROGMEM = { "INICIANDO PUERTA DE ENLACE" };
char const GATEWAY_OK_INIT[] PROGMEM = { "PUERTA DE ENLACE EN OPERACION" };
char const GATEWAY_SMS_SEND[] PROGMEM = { "SMS SALIENTE " };
char const GATEWAY_SMS_RECIBE[] PROGMEM = { "SMS ENTRANTE " };
char const GATEWAY_SALDO_BAJO[] PROGMEM = { "ATENCION: SALDO MENOR A $ " };
char const GATEWAY_GET_SALDO[] PROGMEM = { "CONSULTANDO SALDO DISPONIBLE" };

#endif