#ifndef __ENUMS_H__
#define __ENUMS_H__

enum RF24_Codes {
    RF24_NOTHING,
    B_ERR_START,
    B_ERR_STOP,
    B_ERR_EMERGENCY_STOP,
    B_ERR_TIME_OUT,
    B_ERR_STOP_MANUAL,
    B_ERR_START_MANUAL,
    B_ERR_DISABLE,
    B_ERR_ENABLED,
    B_DISABLE,
    B_ENABLED,
    B_STOP,
    B_START,
    B_MEDIUM_LOW,
    B_MEDIUM_HIGH,
    B_START_MANUAL,
    B_STOP_MANUAL,
    B_ALREDY_ON,
    B_ALREDY_OFF,
    B_ACTUAL_ENABLED,
    B_ACTUAL_DISABLED,
    B_SET_OFF,
    B_SET_ON,
    B_SET_ENABLE,
    B_SET_DISABLE,
    B_GET_LEVEL,
    B_GET_LAST_WORKING,
    B_GET_TEMP,
    B_GET_STATE
};

#endif